In [15]:
import pandas as pd

In [16]:
pd.read_excel (r"C:\Users\Estudiante\Documents\IronHack\Shark attacks\GSAF5.xls")
shark_attack_df =

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,02 Dec-2023,2023.0,Unprovoked,MEXICO,Jalisco,San Patricio Melaque,Swimming,Maria Fernandez Martinez Jimenez,F,26,...,NaN,"News Channel 21, 12/3.2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,30 Nov-2023,2023.0,Unprovoked,AUSTRALIA,Queensland,Clack Island,Swimming,male,M,21,...,1.8m bull shark,"ABC Net, 11/30/2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21 Nov-2023,2023.0,Unprovoked,BAHAMAS,Grand Bahama Island,Tiger Beach,Scuba diving,female,F,47,...,NaN,"Eye Witness News, 11/22/2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10 Nov-2023,2023.0,Unprovoked,AUSTRALIA,South Australia,Port Noarlunga,Free diving,Bridgette Oâ€™Shannessy,F,32,...,NaN,S. DeMarchi. GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,05 Nov-2023,2023.0,Unprovoked,USA,Florida,"Juno Beach, Palm Beach County",Swimming,Steven Reinhardt,M,66,...,NaN,"ABC, 11/15/2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6940,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6943,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN
6944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN